# Generated by Django 5.2.4 on 2025-08-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_teacher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='practice_tradition',
        ),
        migrations.RemoveField(
            model_name='user',
            name='years_practicing',
        ),
    ]
