# Generated by Django 5.2.4 on 2025-08-07 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_favorite_teacher_and_more'),
        ('retreats', '0005_remove_retreat_group_retreat_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='requested', max_length=20, verbose_name='Status')),
                ('requested_date', models.DateTimeField(auto_now_add=True, verbose_name='Requested Date')),
                ('confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed Date')),
                ('cancelled_date', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='retreats.retreatgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Group Membership',
                'verbose_name_plural': 'User Group Memberships',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_us_user_id_45e7f1_idx'), models.Index(fields=['group', 'status'], name='accounts_us_group_i_3134fa_idx')],
                'unique_together': {('user', 'group')},
            },
        ),
    ]
