# Generated by Django 5.2.4 on 2025-08-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usergroupmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_start_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
    ]
