# Generated by Django 5.2.4 on 2025-08-19 20:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoActivationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('original_device_fingerprint', models.CharField(max_length=255, verbose_name='Original Device Fingerprint')),
                ('original_ip', models.GenericIPAddressField(verbose_name='Original IP Address')),
                ('original_user_agent', models.TextField(blank=True, verbose_name='Original User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('used_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Used IP Address')),
                ('used_device_fingerprint', models.CharField(blank=True, max_length=255, verbose_name='Used Device Fingerprint')),
                ('used_user_agent', models.TextField(blank=True, verbose_name='Used User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_activation_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auto Activation Token',
                'verbose_name_plural': 'Auto Activation Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='accounts_au_token_b6bbd2_idx'), models.Index(fields=['user', '-created_at'], name='accounts_au_user_id_6b9622_idx'), models.Index(fields=['expires_at'], name='accounts_au_expires_c542c2_idx')],
            },
        ),
    ]
