# Generated by Django 5.2.4 on 2025-08-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0002_remove_retreat_currency_remove_retreat_is_free_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retreat',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
