# Generated by Django 5.2.4 on 2025-08-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0003_alter_retreat_end_date_alter_retreat_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='time_period',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('full_day', 'Full Day')], default='morning', max_length=20, verbose_name='Time Period'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_date',
            field=models.DateField(verbose_name='Session Date'),
        ),
    ]
