# Generated by Django 5.2.4 on 2025-08-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0004_session_time_period_alter_session_session_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retreat',
            name='group',
        ),
        migrations.AddField(
            model_name='retreat',
            name='groups',
            field=models.ManyToManyField(related_name='retreats', to='retreats.retreatgroup', verbose_name='Groups'),
        ),
    ]
