# Generated by Django 5.2.4 on 2025-08-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0005_remove_retreat_group_retreat_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retreatgroup',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Retreat Group', 'verbose_name_plural': 'Retreat Groups'},
        ),
        migrations.AddField(
            model_name='retreatgroup',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which this group appears in forms', verbose_name='Display Order'),
        ),
    ]
