# Generated by Django 5.2.4 on 2025-08-08 07:10

import utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0006_alter_retreatgroup_options_retreatgroup_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retreatgroup',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterField(
            model_name='retreat',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=utils.storage.RetreatMediaStorage(), upload_to=utils.storage.retreat_image_upload_path, verbose_name='Retreat Image'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=utils.storage.RetreatMediaStorage(), upload_to=utils.storage.retreat_audio_upload_path, verbose_name='Audio File'),
        ),
        migrations.AlterField(
            model_name='track',
            name='transcript_file',
            field=models.FileField(blank=True, null=True, storage=utils.storage.RetreatMediaStorage(), upload_to=utils.storage.retreat_transcript_upload_path, verbose_name='Transcript (PDF)'),
        ),
    ]
