# Generated by Django 5.2.4 on 2025-08-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0007_alter_retreatgroup_options_alter_retreat_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Place Name')),
                ('abbreviation', models.CharField(help_text='Short form like "CCA", "NYC", etc.', max_length=10, verbose_name='Abbreviation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Teacher Name')),
                ('abbreviation', models.CharField(help_text='Short form like "JKR", "MW", etc.', max_length=10, verbose_name='Abbreviation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='retreat',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='retreats', to='retreats.place', verbose_name='Places'),
        ),
        migrations.AddField(
            model_name='retreat',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='retreats', to='retreats.teacher', verbose_name='Teachers'),
        ),
    ]
