# Generated by Django 5.2.4 on 2025-08-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0008_place_teacher_retreat_places_retreat_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='abbreviation',
            field=models.CharField(help_text='Short form like "CCA", "NYC", etc.', max_length=50, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='abbreviation',
            field=models.CharField(help_text='Short form like "JKR", "MW", etc.', max_length=50, verbose_name='Abbreviation'),
        ),
    ]
