# Generated by Django 5.2.4 on 2025-08-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0009_alter_place_abbreviation_alter_teacher_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Accurate duration in seconds', verbose_name='Duration (seconds)'),
        ),
    ]
