# Generated by Django 5.2.4 on 2025-08-26 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0010_add_duration_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Status')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('download_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Download URL')),
                ('s3_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='S3 Key')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='Retry Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('lambda_request_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lambda Request ID')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Processing Started At')),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processing Completed At')),
                ('retreat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to='retreats.retreat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download Request',
                'verbose_name_plural': 'Download Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='retreats_do_user_id_c56677_idx'), models.Index(fields=['retreat', 'status'], name='retreats_do_retreat_a7f654_idx'), models.Index(fields=['status', 'created_at'], name='retreats_do_status_dae08d_idx'), models.Index(fields=['expires_at'], name='retreats_do_expires_7e3404_idx')],
            },
        ),
    ]
