# Generated by Django 5.2.4 on 2025-08-28 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0011_add_download_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this ZIP has been downloaded', verbose_name='Download Count'),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Whether this ZIP is shared among multiple users', verbose_name='Is Shared ZIP'),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, help_text='When this ZIP was last downloaded', null=True, verbose_name='Last Accessed At'),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='popularity_score',
            field=models.FloatField(default=0.0, help_text='Calculated popularity for lifecycle decisions', verbose_name='Popularity Score'),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='shared_zip_key',
            field=models.CharField(blank=True, help_text='S3 key for shared ZIP file', max_length=500, null=True, verbose_name='Shared ZIP Key'),
        ),
        migrations.AddIndex(
            model_name='downloadrequest',
            index=models.Index(fields=['retreat', 'is_shared', 'status'], name='ret_dl_sharing_lookup'),
        ),
        migrations.AddIndex(
            model_name='downloadrequest',
            index=models.Index(fields=['shared_zip_key'], name='ret_dl_shared_key'),
        ),
        migrations.AddIndex(
            model_name='downloadrequest',
            index=models.Index(fields=['last_accessed_at'], name='ret_dl_last_accessed'),
        ),
        migrations.AddIndex(
            model_name='downloadrequest',
            index=models.Index(fields=['popularity_score', 'retreat'], name='ret_dl_popularity'),
        ),
    ]
