# Generated by Django 5.2.4 on 2025-08-30 12:59

import utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0012_add_zip_sharing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=utils.storage.RetreatMediaStorage(), upload_to=utils.storage.retreat_audio_upload_path, verbose_name='Audio File'),
        ),
        migrations.AlterField(
            model_name='track',
            name='transcript_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=utils.storage.RetreatMediaStorage(), upload_to=utils.storage.retreat_transcript_upload_path, verbose_name='Transcript (PDF)'),
        ),
    ]
