# Generated by Django 5.2.4 on 2025-08-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0013_increase_file_field_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='compression_ratio',
            field=models.FloatField(blank=True, help_text='Compression ratio percentage', null=True, verbose_name='Compression Ratio'),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='original_size',
            field=models.PositiveBigIntegerField(blank=True, help_text='Total size of original files before compression', null=True, verbose_name='Original Size (bytes)'),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='performance_metrics',
            field=models.JSONField(blank=True, help_text='Detailed performance breakdown (download_time, zip_time, upload_time)', null=True, verbose_name='Performance Metrics'),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='processed_files',
            field=models.PositiveIntegerField(default=0, help_text='Number of files processed so far', verbose_name='Processed Files'),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='processing_time_seconds',
            field=models.FloatField(blank=True, help_text='Total processing time in seconds', null=True, verbose_name='Processing Time (seconds)'),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Processing progress percentage (0-100)', verbose_name='Progress Percentage'),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='total_files',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of files to process', null=True, verbose_name='Total Files'),
        ),
    ]
