# Generated by Django 5.2.4 on 2025-08-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0014_add_missing_performance_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrequest',
            name='download_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Download URL'),
        ),
    ]
