# Generated by Django 5.2.4 on 2025-09-25 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0016_increase_download_url_to_5000'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['session', 'track_number', 'is_original', 'language'], 'verbose_name': 'Track', 'verbose_name_plural': 'Tracks'},
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('session', 'track_number', 'language')},
        ),
        migrations.AddField(
            model_name='track',
            name='is_original',
            field=models.BooleanField(default=True, help_text='False for translation tracks (auto-detected from filename)', verbose_name='Is Original'),
        ),
        migrations.CreateModel(
            name='UserLanguagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_language_mode', models.CharField(default='en-only', help_text='Default language mode for new retreats (e.g., "en-only", "en-pt", "en-fr")', max_length=20, verbose_name='Default Language Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Language Preference',
                'verbose_name_plural': 'User Language Preferences',
            },
        ),
        migrations.CreateModel(
            name='UserRetreatLanguagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_mode', models.CharField(help_text='Language mode for this specific retreat (e.g., "en-only", "en-pt", "en-fr")', max_length=20, verbose_name='Language Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('retreat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retreats.retreat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Retreat Language Preference',
                'verbose_name_plural': 'User Retreat Language Preferences',
                'unique_together': {('user', 'retreat')},
            },
        ),
    ]
