# Generated by Django 5.2.4 on 2025-09-26 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0017_add_language_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlanguagepreference',
            name='default_language_mode',
        ),
        migrations.AddField(
            model_name='userlanguagepreference',
            name='app_language',
            field=models.CharField(choices=[('en', 'English'), ('pt', 'Português')], default='en', help_text='Default app language for login process and UI', max_length=5, verbose_name='App Language'),
        ),
        migrations.CreateModel(
            name='UserSessionLanguagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_mode', models.CharField(choices=[('en', 'English Only'), ('en-pt', 'English + Portuguese')], help_text='Language mode for this specific session (e.g., "en", "en-pt")', max_length=20, verbose_name='Language Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retreats.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session Language Preference',
                'verbose_name_plural': 'User Session Language Preferences',
                'unique_together': {('user', 'session')},
            },
        ),
        migrations.DeleteModel(
            name='UserRetreatLanguagePreference',
        ),
    ]
