# Generated by Django 5.2.4 on 2025-09-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0018_add_session_language_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlanguagepreference',
            name='content_language',
            field=models.CharField(choices=[('en', 'English Only'), ('en-pt', 'English + Portuguese'), ('pt', 'Portuguese Only')], default='en', help_text='Default content language preference for new devices', max_length=10, verbose_name='Content Language'),
        ),
        migrations.AlterField(
            model_name='userlanguagepreference',
            name='app_language',
            field=models.CharField(choices=[('en', 'English'), ('pt', 'Português')], default='en', help_text='UI language preference set during registration', max_length=5, verbose_name='App Language'),
        ),
        migrations.DeleteModel(
            name='UserSessionLanguagePreference',
        ),
    ]
