# Generated by Django 5.2.4 on 2025-09-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0019_add_content_language_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlanguagepreference',
            name='content_language',
        ),
        migrations.AlterField(
            model_name='userlanguagepreference',
            name='app_language',
            field=models.CharField(choices=[('en', 'English'), ('pt', 'Português')], default='en', help_text='UI language preference set during registration based on frontend language', max_length=5, verbose_name='App Language'),
        ),
    ]
